name: build and push gatsby

on:
  schedule:
    # every month
    - cron: '0 2 1 * *'
  push:
    branches:
      - master

jobs:
  build-image:
    name: build gatsby images and push
    runs-on: ubuntu-latest

    steps:
      - name: set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: checkout
        uses: actions/checkout@v2

      - name: ensure it works
        run: make test

      - name: build and push
        run: make build-latest
        env:
          BUILD_ARGS: "--push"
